apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
      - name: payment
        image: reactivesw/payment:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: server_port
          value: "80"
        - name: spring_datasource_url
          value: jdbc:postgresql://pg-data/payment
        - name: spring_cloud_config_uri
          value: http://reactivesw-config