server:
  port: 8087

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  profiles:
    active: test

io:
  reactivesw:
    message:
      brokerType: google
      google:
        project:
          id: reactivesw-project

braintree:
  environment: "sanbox"
  merchantid: "your merchant id"
  publickey: "your public key"
  privatekey: "your private key"