server:
  port: 8087

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  profiles:
    active: test

io:
  reactivesw:
    message:
      topic:
        ordercreated:
          subscriber: dev-payment-order-pay
        paymentpayed:
          name: reactivesw-dev-payment-payed
          version: 1
      brokerType: google
      google:
        project:
          id: reactivesw-project2

aes:
  secret:
    key: DSihgbfnrXR3FLNj